# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lint, Test, build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x", "20.x", "22.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Lint code
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test code
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: yarn test:ci
      - uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: .test/test-results.junit

  build:
    needs: 
      - test
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build source code
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: yarn build

  semver:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
